import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import mongoSanitize from 'express-mongo-sanitize';
import auth from './routes/auth.js';
import profile from './routes/profile.js';
import skills from './routes/skills.js';
import experience from './routes/experience.js';
import projects from './routes/projects.js';
import education from './routes/education.js';
import certifications from './routes/certifications.js';
import achievements from './routes/achievements.js';
import messages from './routes/messages.js';
import resume from './routes/resume.js';
import settings from './routes/settings.js';
import {errorMiddleware} from './middleware/error.js';
const app=express();
app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:process.env.CLIENT_URL,credentials:true}));
app.use(express.json({limit:'250kb'}));
app.use(cookieParser(process.env.COOKIE_SECRET));
app.use(mongoSanitize());
app.get('/api/health',(req,res)=>res.json({success:true,data:{status:'ok'}}));
app.use('/api/auth',auth);
app.use('/api/profile',profile);
app.use('/api/skills',skills);
app.use('/api/experience',experience);
app.use('/api/projects',projects);
app.use('/api/education',education);
app.use('/api/certifications',certifications);
app.use('/api/achievements',achievements);
app.use('/api/messages',messages);
app.use('/api/resume',resume);
app.use('/api/settings',settings);
app.use((req,res)=>res.status(404).json({success:false,message:'Route not found'}));
app.use(errorMiddleware);
export default app;