import { Outlet, Link, useLocation, useNavigate } from 'react-router-dom';
import { Award, BadgeCheck, Briefcase, FileText, FolderKanban, GraduationCap, LayoutDashboard, LogOut, Menu, MessageSquare, Settings, Trophy, User, X } from 'lucide-react';
import { useState } from 'react';
import { api } from '../services/api.js';

const nav = [{ to: '/admin/dashboard', label: 'Dashboard', icon: LayoutDashboard }, { to: '/admin/profile', label: 'Profile', icon: User }, { to: '/admin/skills', label: 'Skills', icon: Award }, { to: '/admin/experience', label: 'Experience', icon: Briefcase }, { to: '/admin/projects', label: 'Projects', icon: FolderKanban }, { to: '/admin/education', label: 'Education', icon: GraduationCap }, { to: '/admin/certifications', label: 'Certifications', icon: BadgeCheck }, { to: '/admin/achievements', label: 'Achievements', icon: Trophy }, { to: '/admin/messages', label: 'Messages', icon: MessageSquare }, { to: '/admin/resume', label: 'Resume', icon: FileText }, { to: '/admin/settings', label: 'Settings', icon: Settings }];

export default function AdminLayout() {
  const [open, setOpen] = useState(false); const navigate = useNavigate(); const location = useLocation();
  async function logout() { try { await api.auth.logout(); } finally { navigate('/admin/login'); } }
  const links = <nav className="grid gap-1">{nav.map(({ to, label, icon: Icon }) => <Link key={to} to={to} onClick={() => setOpen(false)} className={`flex items-center gap-3 border-l-2 px-3 py-2 text-sm ${location.pathname === to ? 'border-cyan-400 bg-slate-800 text-slate-100' : 'border-transparent text-slate-400 hover:bg-slate-900 hover:text-slate-100'}`}><Icon size={17} />{label}</Link>)}</nav>;
  return <div className="flex min-h-screen bg-slate-950 text-slate-100"><aside className="hidden w-64 shrink-0 border-r border-slate-800 bg-slate-950 p-4 md:flex md:flex-col"><Link to="/admin/dashboard" className="flex items-center gap-3 px-2 py-3 font-semibold"><span className="grid h-8 w-8 place-items-center border border-cyan-800 bg-cyan-950 font-mono text-xs text-cyan-300">MK</span>Control panel</Link><div className="mt-7 flex-1">{links}</div><button onClick={logout} className="btn-secondary w-full"><LogOut size={16} />Logout</button></aside><div className="flex min-w-0 flex-1 flex-col"><header className="flex h-16 items-center justify-between border-b border-slate-800 px-4"><button onClick={() => setOpen(value => !value)} className="grid h-9 w-9 place-items-center border border-slate-700 md:hidden" aria-label="Toggle admin navigation">{open ? <X size={18} /> : <Menu size={18} />}</button><p className="font-mono text-xs text-slate-500">PORTFOLIO / ADMIN</p><button onClick={logout} className="hidden text-sm text-slate-400 hover:text-slate-100 md:block">Logout</button></header>{open && <div className="border-b border-slate-800 bg-slate-950 p-3 md:hidden">{links}</div>}<main className="flex-1 p-4 sm:p-7"><Outlet /></main></div></div>;
}
